const $=id=>document.getElementById(id);
const {phases,slots,exercises:EX,rehab,strengthA:A,strengthB:B,rotations,labels}=window.BANGTAO;
const STORAGE_KEY='bangtao12';
function store(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"week":1,"slots":["mon","wed","fri"],"days":[],"weekDone":{},"choice":{}}')}catch{return {week:1,slots:['mon','wed','fri'],days:[],weekDone:{},choice:{}}}}
function put(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function todayKey(){return new Date().toISOString().slice(0,10)}
function weekKey(d=new Date()){let x=new Date(d),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x.toISOString().slice(0,10)}
function doneState(){const s=store(),k=weekKey();return s.weekDone?.[k]||{A:false,B:false,bike:false,shadow:false,kb:0}}
function available(){const d=doneState();return rotations.filter(x=>x==='kb'||x==='recovery'||!d[x])}
function suggested(){const d=doneState(),day=new Date().getDay();if(day===6&&!d.A)return'A';if(day===0&&!d.B)return'B';if(!d.A)return'A';if(!d.B)return'B';if(!d.bike)return'bike';if(!d.shadow)return'shadow';if(d.kb<3)return'kb';return'recovery'}
function chosen(){const s=store(),key=todayKey(),a=available(),c=s.choice?.[key];return a.includes(c)?c:suggested()}
function chooseWorkout(v){const s=store(),key=todayKey();s.choice=s.choice||{};s.choice[key]=v;put(s);renderToday()}
function cycleWorkout(dir){const a=available(),i=a.indexOf(chosen());chooseWorkout(a[(i+dir+a.length)%a.length])}
window.chooseWorkout=chooseWorkout;window.cycleWorkout=cycleWorkout;
let ac;function audio(){if(!ac)ac=new(window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')ac.resume();return ac}
function tone(f,d=.06,v=.04,type='sine'){const c=audio(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d)}
function tick(){tone(850,.04,.025,'square')}function beep(){tone(1250,.18,.07,'square')}function ding(){tone(900,.15,.06);setTimeout(()=>tone(1350,.28,.06),120)}
const timers={};
function countdown(id,secs,done){audio();if(timers[id]){clearInterval(timers[id]);delete timers[id];return}const b=$(id);let r=secs+3;b.classList.add('running');b.querySelector('.count').textContent='Ready 3';tick();timers[id]=setInterval(()=>{r--;if(r>secs){b.querySelector('.count').textContent='Ready '+(r-secs);tick()}else if(r===secs){b.querySelector('.count').textContent=fmt(r);beep()}else b.querySelector('.count').textContent=fmt(r);if(r<=0){clearInterval(timers[id]);delete timers[id];b.classList.remove('running');b.querySelector('.count').textContent='Done';const box=$(done);if(box)box.checked=true;ding()}},1000)}
window.countdown=countdown;
function repRows(k,label,side,weight){const e=EX[k];let h=label?`<div class="side">${label}</div>`:'';h+=`<div class="sethead"><span>SET</span><span>REPS</span><span>${weight?'LB':''}</span><span>✓</span></div>`;for(let i=1;i<=e[1];i++)h+=`<div class="setrow"><b>${i}</b><input id="${k}_${side}_r${i}" type="number" value="${e[2]}">${weight?`<input id="${k}_${side}_w${i}" type="number" placeholder="0">`:'<span></span>'}<input id="${k}_${side}_d${i}" type="checkbox"></div>`;return h}
function towelRows(k){const e=EX[k];let h='';for(const [label,side] of [['Left foot','left'],['Right foot','right']]){h+=`<div class="side">${label}</div>`;for(let i=1;i<=e[1];i++)h+=`<div class="complete"><span>Set ${i} · scrunch entire towel</span><input id="${k}_${side}_d${i}" type="checkbox"></div>`}return h}
function timerRows(k,label,side){const e=EX[k];let h=label?`<div class="side">${label}</div>`:'';for(let i=1;i<=e[1];i++){const id=`t_${k}_${side}_${i}`,done=`${k}_${side}_d${i}`;h+=`<button id="${id}" class="timerbtn" onclick="countdown('${id}',${e[2]},'${done}')"><span>Set ${i}</span><span class="count">${fmt(e[2])}</span></button><div class="complete"><span class="micro">tick · tick · tick · BEEP to start</span><input id="${done}" type="checkbox"></div>`}return h}
function tracking(k){const m=EX[k][3];if(m==='weight')return repRows(k,'','both',true);if(m==='weight-side')return repRows(k,'Left','left',true)+repRows(k,'Right','right',true);if(m==='reps')return repRows(k,'','both',false);if(m==='reps-side')return repRows(k,'Left','left',false)+repRows(k,'Right','right',false);if(m==='timed-side')return timerRows(k,'Left side','left')+timerRows(k,'Right side','right');if(m==='timed-foot')return timerRows(k,'Left foot','left')+timerRows(k,'Right foot','right');if(m==='towel-foot')return towelRows(k);return timerRows(k,'','both')}
function metaText(e){if(e[3]==='towel-foot')return `${e[1]} sets · entire towel each set`;if(e[3].startsWith('timed'))return `${e[1]} sets · ${fmt(e[2])}`;return `${e[1]} sets · ${e[2]} reps`}
function card(k,track=true){const e=EX[k];return `<div class="exercise"><div class="title">${e[0]}</div><div class="meta">${metaText(e)}</div><div class="muted">${e[4]}</div>${track?tracking(k):''}<details><summary>Show tutorial</summary><div class="video"><iframe src="https://www.youtube.com/embed/${e[5]}" title="${e[0]} tutorial" loading="lazy" allowfullscreen></iframe></div><a class="ytlink" target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=${e[5]}">Open on YouTube ↗</a></details></div>`}
let bikeTimer;
function bikeCard(mins){return `<div class="exercise"><div class="title">Stationary bike</div><div class="muted">Steady conversational effort.</div><div class="bikegrid"><label>Actual minutes <input id="bike_actual" type="number" placeholder="0"></label><button class="secondary bikebtn" id="bike_main" onclick="bikeStart(${mins})">Start ${mins}:00</button><div class="complete"><span>Completed</span><input id="bike_done" type="checkbox"></div></div></div>`}
function bikeStart(mins){audio();if(bikeTimer){clearInterval(bikeTimer);bikeTimer=null;return}let r=mins*60+3,b=$('bike_main');b.textContent='Ready 3';tick();bikeTimer=setInterval(()=>{r--;if(r>mins*60){b.textContent='Ready '+(r-mins*60);tick()}else if(r===mins*60){b.textContent=fmt(r);beep()}else b.textContent=fmt(r);if(r<=0){clearInterval(bikeTimer);bikeTimer=null;b.textContent='Done';$('bike_actual').value=mins;$('bike_done').checked=true;ding()}},1000)}
window.bikeStart=bikeStart;
function renderToday(){const s=store(),w=s.week||1,p=phases[w],pain=+$('pain').value||0,a=available();let c=chosen();$('workoutChoice').innerHTML=a.map(x=>`<option value="${x}" ${x===c?'selected':''}>${labels[x]}</option>`).join('');$('suggestion').textContent='Suggested: '+labels[suggested()];if(pain>=5&&['A','B','shadow'].includes(c))c='recovery';let h='';if(c==='A')h=A.map(x=>card(x)).join('')+'<div class="complete"><span>Mark Strength A complete</span><input id="workout_complete" type="checkbox"></div>';else if(c==='B')h=B.map(x=>card(x)).join('')+'<div class="complete"><span>Mark Strength B complete</span><input id="workout_complete" type="checkbox"></div>';else if(c==='bike')h=bikeCard(p[1]);else if(c==='shadow')h=card('teephold')+card('shadow')+'<div class="complete"><span>Mark shadow + teep complete</span><input id="workout_complete" type="checkbox"></div>';else h=`<div class="exercise"><div class="title">${labels[c]}</div><div class="complete"><span>Completed</span><input id="workout_complete" type="checkbox"></div></div>`;$('todayPlan').innerHTML=h;$('warning').textContent=pain>=5?'High symptom day. Keep impact low. Rehab and gentle mobility still stay in.':'Proceed with the plan. Daily rehab + mobility stays in.';restoreToday()}
function renderRehab(){$('rehab').innerHTML=rehab.map(x=>card(x)).join('')}
function renderProgram(){const s=store(),w=s.week||1,p=phases[w],d=doneState();$('weekpill').textContent=`Week ${w} of 7`;$('phase').textContent=p[0];$('focus').textContent=`Bike ${p[1]} min. Shadowboxing ${p[2]} rounds. Rehab every day.`;$('weekSelect').value=w;$('slots').innerHTML=slots.map(x=>`<div class="slot"><b>${x[2]}</b><input id="slot_${x[0]}" type="checkbox" ${(s.slots||[]).includes(x[0])?'checked':''}></div>`).join('');$('weeklyStatus').innerHTML=['A','B','bike','shadow'].map(x=>`<div class="day"><b>${labels[x]}</b> · ${d[x]?'Complete':'Remaining'}</div>`).join('')+`<div class="day"><b>Kickboxing</b> · ${d.kb||0} / 3 to 4</div>`;const names=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];$('weekPlan').innerHTML=names.map((n,i)=>`<div class="day"><b>${n}</b><div class="muted">${i===6&&!d.A?'Preferred: Strength A':i===0&&!d.B?'Preferred: Strength B':'Choose from remaining rotation'}</div><div class="muted">+ Daily rehab + mobility</div></div>`).join('')}
function saveSlots(){const s=store();s.slots=slots.filter(x=>$('slot_'+x[0]).checked).map(x=>x[0]);put(s);renderProgram()}window.saveSlots=saveSlots;
function setWeek(w){const s=store();s.week=+w;put(s);renderProgram();renderToday()}window.setWeek=setWeek;
let sess=null,elapsed=0;function startSession(){if(sess){clearInterval(sess);sess=null;return}sess=setInterval(()=>{elapsed++;$('sessionTime').textContent=fmt(elapsed)},1000)}window.startSession=startSession;
function saveToday(){const s=store(),key=todayKey(),c=chosen(),fields={};document.querySelectorAll('#today input').forEach(e=>fields[e.id]=e.type==='checkbox'?e.checked:e.value);const complete=c==='bike'?!!$('bike_done')?.checked:!!$('workout_complete')?.checked;s.days=(s.days||[]).filter(x=>x.date!==key);s.days.push({date:key,pain:+$('pain').value||0,choice:c,complete,fields,notes:$('notes').value,elapsed});if(complete){const wk=weekKey();s.weekDone=s.weekDone||{};const d=s.weekDone[wk]||{A:false,B:false,bike:false,shadow:false,kb:0};if(c==='kb')d.kb=(d.kb||0)+1;else if(['A','B','bike','shadow'].includes(c))d[c]=true;s.weekDone[wk]=d}put(s);alert('Saved.');renderToday();renderProgram()}window.saveToday=saveToday;
function restoreToday(){const x=(store().days||[]).find(x=>x.date===todayKey());if(!x)return;Object.entries(x.fields||{}).forEach(([id,v])=>{const e=$(id);if(e)e.type==='checkbox'?e.checked=v:e.value=v});$('notes').value=x.notes||'';elapsed=x.elapsed||0;$('sessionTime').textContent=fmt(elapsed)}
function progress(){const d=store().days||[];$('logged').textContent=d.length;$('avg').textContent=(d.length?d.reduce((a,x)=>a+x.pain,0)/d.length:0).toFixed(1);$('history').innerHTML=d.slice().reverse().slice(0,14).map(x=>`<div class="day"><b>${x.date}</b> · ${labels[x.choice]||x.choice||''} · pain ${x.pain}/10</div>`).join('')}
function show(n){document.querySelectorAll('section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));$(n).classList.add('active');$('tab'+n[0].toUpperCase()+n.slice(1)).classList.add('active');if(n==='progress')progress()}window.show=show;
$('weekSelect').innerHTML=[1,2,3,4,5,6,7].map(x=>`<option value="${x}">Week ${x}</option>`).join('');$('date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});$('pain').oninput=renderToday;$('trend').onchange=renderToday;renderRehab();renderProgram();renderToday();$('libraryList').innerHTML=Object.keys(EX).map(x=>card(x,false)).join('');