window.BANGTAO = {
  phases:{1:['Foundation',30,3],2:['Foundation',35,3],3:['Build',40,4],4:['Build',45,4],5:['Specific',50,5],6:['Specific',55,6],7:['Taper',30,3]},
  slots:[['mon',1,'Monday evening'],['tue',2,'Tuesday noon'],['wed',3,'Wednesday evening'],['thu',4,'Thursday noon'],['fri',5,'Friday evening'],['sat',6,'Saturday'],['sun',0,'Sunday']],
  exercises:{
    squat:['Goblet squat',3,12,'weight','Controlled depth. Stay 2 to 3 reps from failure.','MeIiIdhvXT4'],
    rdl:['Romanian deadlift',3,8,'weight','Hinge back. Soft knees. Neutral spine.','3VXmecChYYM'],
    bench:['Barbell bench press',3,8,'weight','Controlled reps. No grinding.','rT7DgCr-3pg'],
    pull:['Lat pulldown',3,10,'weight','Full controlled range. Drive elbows down.','43hWj8mfYGY'],
    pullup:['Pull ups',3,8,'reps','Start from a controlled hang. Pull chest toward the bar and avoid swinging.','eGo4IYlbE5g'],
    legraise:['Hanging leg raise',3,12,'reps','Control the pelvis. Avoid swinging.','Pr1ieGZ5atk'],
    kneedrive:['Standing banded knee drive',3,12,'reps-side','Drive knee toward teep chamber height. Stay tall and control the return.','yO292ml-IVU'],
    straightleg:['Seated straight leg lift',3,12,'weight-side','Sit tall. Keep knee straight and lift heel with control. Add load only if you can maintain the same clean motion.','iWGr0-dXqww'],
    teephold:['Teep chamber hold',3,25,'timed-side','Bring knee high into teep chamber and hold tall.','s3uW3XSOdvA'],
    tib:['Tibialis raise',3,15,'reps','Heels down. Pull toes toward shins.','boFuKPm5w2Q'],
    split:['Rear foot elevated split squat',3,10,'weight-side','Controlled depth.','bwhl_9jN_3o'],
    slrdl:['Single leg RDL',3,10,'weight-side','Keep hips square.','Zfr6wizR8rs'],
    row:['Cable row',3,12,'weight','Keep ribs stacked.','UCXxvVItLoM'],
    copenhagen:['Copenhagen plank',3,30,'timed-side','Keep hips stacked and use a shorter lever if needed.','1NNqUQvMYGc'],
    farmer:['Farmer carry',3,30,'carry-weight','Hold equal weight in both hands and walk tall. Track the weight in each hand.','rt17lmnaLSM'],
    standingcalf:['Standing calf raise',3,12,'reps','Use support. Lower slowly.','gwLzBJYoWlI'],
    plantar:['Plantar fascia stretch',3,30,'timed-foot','Cross the foot over the opposite knee and gently pull the toes toward the shin.','VwbDxqV_XhA'],
    straight:['Straight knee calf stretch',3,30,'timed-foot','Back knee straight and heel down.','eleOWUIwtco'],
    ballraise:['Ball squeeze heel raise',3,12,'reps','Place a small ball between both heels, squeeze gently, and raise both heels together with control.','IzXhuC6WTAA'],
    balance:['Single leg reach balance',3,30,'timed-foot','Stand on one foot. Move the other foot forward, side, and back with control for the full 30 seconds.','UoMSMdMKfBY'],
    hipstretch:['Half kneeling hip flexor stretch',2,30,'timed-side','Tuck pelvis, squeeze rear glute and move forward gently.','gqoPYLUgP48'],
    towel:['Towel scrunch',3,1,'towel-both','Place both feet on the towel and scrunch it toward you with both sets of toes. One full towel equals one set.','cnflVnYyGpc'],
    shadow:['Muay Thai shadowboxing',3,180,'timed','Relaxed technical rounds. Minimal bouncing while the foot is irritated.','s3uW3XSOdvA']
  },
  rehab:['plantar','straight','ballraise','balance','hipstretch','standingcalf','towel'],
  strengthA:['squat','rdl','bench','pull','legraise','kneedrive','tib'],
  strengthB:['split','slrdl','row','copenhagen','pullup','straightleg','farmer','standingcalf'],
  rotations:['A','B','bike','shadow','kb','recovery'],
  labels:{A:'Strength A',B:'Strength B',bike:'Stationary bike',shadow:'Shadowboxing + teep',kb:'Kickboxing',recovery:'Recovery'}
};