window.BANGTAO = {
  phases:{1:['Foundation',30,3],2:['Foundation',35,3],3:['Build',40,4],4:['Build',45,4],5:['Specific',50,5],6:['Specific',55,6],7:['Taper',30,3]},
  slots:[['mon',1,'Monday evening'],['tue',2,'Tuesday noon'],['wed',3,'Wednesday evening'],['thu',4,'Thursday noon'],['fri',5,'Friday evening'],['sat',6,'Saturday'],['sun',0,'Sunday']],
  exercises:{
    squat:['Goblet squat',3,12,'weight','Controlled depth. Stay 2 to 3 reps from failure.','MeIiIdhvXT4'],
    rdl:['Romanian deadlift',3,8,'weight','Hinge back. Soft knees. Neutral spine.','3VXmecChYYM'],
    bench:['Barbell bench press',3,8,'weight','Controlled reps. No grinding.','rT7DgCr-3pg'],
    pull:['Lat pulldown',3,10,'weight','Full controlled range. Drive elbows down.','43hWj8mfYGY'],
    pullup:['Pull ups',3,8,'reps','Start from a controlled hang. Pull chest toward the bar and avoid swinging.','eGo4IYlbE5g'],
    legraise:['Hanging leg raise',3,12,'reps','Control the pelvis. Avoid swinging.','Pr1ieGZ5atk'],
    kneedrive:['Standing banded knee drive',3,12,'reps-side','Drive knee toward teep chamber height. Stay tall and control the return.','yO292ml-IVU'],
    straightleg:['Seated straight leg lift',3,12,'weight-side','Sit tall. Keep knee straight and lift heel with control. Add load only if you can maintain the same clean motion.','iWGr0-dXqww'],
    teephold:['Teep chamber hold',3,25,'timed-side','Bring knee high into teep chamber and hold tall.','s3uW3XSOdvA'],
    tib:['Tibialis raise',3,15,'reps','Up as high as you can, down toward the big toe, up as high as you can, down toward the pinky toe. Repeat.','boFuKPm5w2Q'],
    split:['Rear foot elevated split squat',3,10,'weight-side','Controlled depth.','bwhl_9jN_3o'],
    slrdl:['Single leg RDL',3,10,'weight-side','Keep hips square. Use light weight or fingertip support if balance limits the movement. Treat this as controlled balance practice, not a max strength exercise.','Zfr6wizR8rs'],
    swing:['Kettlebell swing',3,12,'weight','Explosive hip snap, not a squat. Keep the sets crisp and stop before fatigue slows the swing.','YSxHifyI6s8'],
    row:['Cable row',3,12,'weight','Keep ribs stacked.','UCXxvVItLoM'],
    copenhagen:['Copenhagen plank',3,30,'timed-side','Keep hips stacked and use a shorter lever if needed.','1NNqUQvMYGc'],
    farmer:['Farmer carry',3,30,'carry-weight','Hold equal weight in both hands and walk tall. Track the weight in each hand.','rt17lmnaLSM'],
    standingcalf:['Standing calf raise from floor',3,12,'weight','Use support if needed. Start and finish on flat ground. Rise through the ball of the foot, pause at the top, and lower slowly. Do not let the heel drop below floor level while the Achilles insertion is irritated.','gwLzBJYoWlI'],
    plantar:['Plantar fascia stretch',3,30,'timed-foot','Cross the foot over the opposite knee and gently pull the toes toward the shin. Keep the ankle relaxed so you stretch the plantar fascia without forcing the Achilles.','VwbDxqV_XhA'],
    towel:['Towel scrunch',3,1,'towel-both','Use the toes to scrunch the towel while keeping the heel planted. This trains the foot intrinsics with very little Achilles loading. Stop if it increases heel pain.','cnflVnYyGpc'],
    achillesiso:['Achilles calf raise isometric',4,30,'timed','On flat ground, rise onto both toes and hold. Keep the heel above floor level without bouncing. Use daily as tolerated for symptom-friendly loading. Stop if insertion pain clearly increases.','gwLzBJYoWlI'],
    seatedcalf:['Seated calf raise',3,15,'weight','Do 3 to 4 days per week. Keep the foot flat enough that the heel starts from neutral, then raise the heel slowly. Add load gradually. Skip this if the Achilles is clearly worse the next morning.','JbyjNymZOt0'],
    bandhop:['In and out banded hops',3,20,'timed','High Achilles load. Skip while insertion pain is 3/10 or higher or worse the next morning. When cleared, stay light and quick.','mGKP8uonWas'],
    stancepush:['Explosive stance push offs',3,20,'timed','High Achilles load. Skip while insertion pain is 3/10 or higher or worse the next morning. Reintroduce gradually.','mGKP8uonWas'],
    bandhighknee:['Banded high knee drives',3,20,'timed','Band around the midfoot or arches. Rapidly drive one knee toward waist height, alternate sides, and stay tall.','mGKP8uonWas'],
    switchknees:['Banded continuous switch knees',3,20,'timed','High Achilles load because of the fast foot switches. Skip while insertion pain is 3/10 or higher or worse the next morning.','mGKP8uonWas'],
    shadow:['Muay Thai shadowboxing',3,180,'timed','Relaxed technical rounds. Minimal bouncing while the foot is irritated.','s3uW3XSOdvA'],
    shoulderpress:['Dumbbell shoulder press',3,10,'weight','Press with control. Keep 2 to 3 reps in reserve; this is accessory work, not a max-effort lift.','qEwKCR5JCog'],
    lateralraise:['Dumbbell lateral raise',3,15,'weight','Raise with control to about shoulder height. Keep the weight light enough to avoid swinging.','3VcKaXpzqRo'],
    curl:['Dumbbell biceps curl',3,12,'weight','Keep elbows controlled and avoid using momentum.','ykJmrZ5v0Oo'],
    pushdown:['Cable triceps pushdown',3,12,'weight','Keep elbows near your sides and fully extend without leaning into the movement.','2-LAMcpzODU'],
    jumprope:['Jump rope',5,60,'timed','High repetitive Achilles load. Skip if Achilles insertion pain is 3/10 or higher, plantar pain is elevated, or either area is worse the next morning. Substitute easy bike work.','u3zgHI8QnqE']
  },
  rehab:['plantar','towel','achillesiso','seatedcalf','standingcalf'],
  strengthA:['squat','rdl','bench','pull','legraise','kneedrive','tib'],
  strengthB:['split','slrdl','swing','row','copenhagen','pullup','straightleg','farmer','standingcalf'],
  upper:['shoulderpress','lateralraise','curl','pushdown','jumprope'],
  bikeDrills:['bandhop','stancepush','bandhighknee','switchknees'],
  rotations:['A','B','upper','bike','shadow','kb','recovery'],
  labels:{A:'Strength A',B:'Strength B',upper:'Upper + cardio',bike:'Stationary bike + band drills',shadow:'Shadowboxing + teep',kb:'Kickboxing',recovery:'Recovery'}
};