(()=>{
 const active={};let ctx=null;
 const fmt=n=>`${String(Math.floor(Math.max(0,n)/60)).padStart(2,'0')}:${String(Math.max(0,n)%60).padStart(2,'0')}`;
 function setAmbient(){try{if(navigator.audioSession&&'type'in navigator.audioSession)navigator.audioSession.type='ambient'}catch{}}
 function freshAudio(){setAmbient();try{if(ctx&&ctx.state==='closed')ctx=null;if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended'||ctx.state==='interrupted')ctx.resume().catch(()=>{})}catch{}return ctx}
 function unlock(){const c=freshAudio();if(!c)return;try{const b=c.createBuffer(1,1,22050),s=c.createBufferSource();s.buffer=b;s.connect(c.destination);s.start()}catch{}}
 function tone(f,d=.16,gain=.22,delay=0){const c=freshAudio();if(!c)return;try{const w=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,w);g.gain.exponentialRampToValueAtTime(gain,w+.01);g.gain.exponentialRampToValueAtTime(.0001,w+d);o.connect(g);g.connect(c.destination);o.start(w);o.stop(w+d+.03)}catch{}}
 function cue(){tone(1050,.07,.12)}
 function startBeep(){tone(1250,.12,.18);tone(1650,.14,.18,.14)}
 function alarm(){tone(1100,.18,.24);tone(1500,.18,.24,.22);tone(1950,.28,.26,.44);try{navigator.vibrate?.([180,80,180])}catch{}}
 window.BangtaoAudio={unlock,cue,start:startBeep,alarm,resume:()=>{if(ctx&&ctx.state==='running'){const old=ctx;setTimeout(()=>old.suspend().then(()=>old.resume()).catch(()=>{}),30)}else freshAudio()}};
 ['pointerdown','touchstart','click'].forEach(e=>document.addEventListener(e,unlock,{once:true,capture:true}));
 function clear(id){const t=active[id];if(!t)return;clearInterval(t.i);delete active[id]}
 function finish(id,late=false){const t=active[id];if(!t)return;clearInterval(t.i);delete active[id];const b=document.getElementById(id);if(b){b.classList.remove('running');const x=b.querySelector('.count');if(x)x.textContent='Done'}const box=document.getElementById(t.done);if(box&&!box.checked){box.checked=true;box.dispatchEvent(new Event('change',{bubbles:true}))}alarm()}
 function refresh(id){const t=active[id];if(!t)return;const b=document.getElementById(id);if(!b){clear(id);return}const now=Date.now();if(now>=t.end){finish(id,true);return}const x=b.querySelector('.count');if(now<t.start){if(x)x.textContent='Ready '+Math.max(1,Math.ceil((t.start-now)/1000));return}const r=Math.ceil((t.end-now)/1000);if(x)x.textContent=fmt(r)}
 function countdown(id,seconds,done){unlock();const b=document.getElementById(id);if(!b)return;if(active[id]){clear(id);b.classList.remove('running');return}const start=Date.now()+3000,end=start+seconds*1000;b.classList.add('running');const x=b.querySelector('.count');if(x)x.textContent='Ready 3';cue();setTimeout(()=>active[id]&&cue(),1000);setTimeout(()=>active[id]&&cue(),2000);setTimeout(()=>active[id]&&startBeep(),3000);active[id]={done,start,end,i:setInterval(()=>refresh(id),200)};refresh(id)}
 window.countdown=countdown;window.countdownFromInput=(id,input,done)=>countdown(id,Math.max(1,parseInt(document.getElementById(input)?.value)||30),done);
 let bike=null;
 window.bikeStart=min=>{unlock();const b=document.getElementById('bike_main');if(!b)return;if(bike){clearInterval(bike.i);bike=null;b.textContent=`Start ${min}:00`;return}const start=Date.now()+3000,end=start+min*60000;cue();const update=()=>{if(!bike)return;const now=Date.now();if(now>=end){clearInterval(bike.i);bike=null;b.textContent='Done';const a=document.getElementById('bike_actual'),d=document.getElementById('bike_done');if(a)a.value=min;if(d){d.checked=true;d.dispatchEvent(new Event('change',{bubbles:true}))}alarm();return}if(now<start)b.textContent='Ready '+Math.max(1,Math.ceil((start-now)/1000));else b.textContent=fmt(Math.ceil((end-now)/1000))};setTimeout(()=>bike&&cue(),1000);setTimeout(()=>bike&&cue(),2000);setTimeout(()=>bike&&startBeep(),3000);bike={start,end,i:setInterval(update,200)};update()};
 document.addEventListener('visibilitychange',()=>{if(!document.hidden){window.BangtaoAudio.resume();Object.keys(active).forEach(refresh);if(bike){const b=document.getElementById('bike_main');if(Date.now()>=bike.end){clearInterval(bike.i);const min=Math.round((bike.end-bike.start)/60000);bike=null;if(b)b.textContent='Done';const a=document.getElementById('bike_actual'),d=document.getElementById('bike_done');if(a)a.value=min;if(d){d.checked=true;d.dispatchEvent(new Event('change',{bubbles:true}))}alarm()}}}});
 setAmbient();
})();