(()=>{
 const active={};let ctx=null,unlocked=false;
 function getAudio(){try{if(navigator.audioSession&&'type'in navigator.audioSession)navigator.audioSession.type='playback'}catch{};if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume().catch(()=>{});return ctx}
 function unlock(){try{const c=getAudio(),b=c.createBuffer(1,1,22050),s=c.createBufferSource();s.buffer=b;s.connect(c.destination);s.start();unlocked=true}catch{}}
 ['pointerdown','touchstart','click'].forEach(e=>document.addEventListener(e,unlock,{once:true,capture:true}));
 function tone(c,w,f,d=.18,gain=.5,type='square'){const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,w);g.gain.exponentialRampToValueAtTime(gain,w+.01);g.gain.exponentialRampToValueAtTime(.0001,w+d);o.connect(g);g.connect(c.destination);o.start(w);o.stop(w+d+.03);return o}
 function tick(){const c=getAudio();tone(c,c.currentTime+.01,1100,.08,.3)}
 function clear(id){const t=active[id];if(!t)return;clearInterval(t.i);(t.nodes||[]).forEach(n=>{try{n.stop()}catch{}});delete active[id]}
 function finish(id){const t=active[id];if(!t)return;clearInterval(t.i);delete active[id];const b=document.getElementById(id);if(b){b.classList.remove('running');const x=b.querySelector('.count');if(x)x.textContent='Done'}const box=document.getElementById(t.done);if(box){box.checked=true;box.dispatchEvent(new Event('change',{bubbles:true}))}}
 function refresh(id){const t=active[id];if(!t)return;const b=document.getElementById(id);if(!b){clear(id);return}const ms=t.end-Date.now();if(ms<=0){finish(id);return}const r=Math.ceil(ms/1000),x=b.querySelector('.count');if(x)x.textContent=`${String(Math.floor(r/60)).padStart(2,'0')}:${String(r%60).padStart(2,'0')}`}
 function countdown(id,seconds,done){unlock();const b=document.getElementById(id);if(!b)return;if(active[id]){clear(id);b.classList.remove('running');return}const c=getAudio(),start=Date.now()+3000,end=start+seconds*1000,a=c.currentTime+3,z=a+seconds,nodes=[];b.classList.add('running');const x=b.querySelector('.count');if(x)x.textContent='Ready 3';tick();setTimeout(()=>active[id]&&tick(),1000);setTimeout(()=>active[id]&&tick(),2000);try{[1500,1950].forEach((f,i)=>nodes.push(tone(c,a+i*.22,f,.2,.55)));[1200,1650,2150].forEach((f,i)=>nodes.push(tone(c,z+i*.24,f,i===2?.4:.22,.6)))}catch{};active[id]={done,start,end,nodes,i:setInterval(()=>{const t=active[id];if(!t)return;const now=Date.now();if(now<t.start){if(x)x.textContent='Ready '+Math.max(1,Math.ceil((t.start-now)/1000))}else refresh(id)},200)}}
 window.countdown=countdown;window.countdownFromInput=(id,input,done)=>countdown(id,Math.max(1,parseInt(document.getElementById(input)?.value)||30),done);
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)Object.keys(active).forEach(refresh)});
})();